"""Build the modular SmartCare medical-navigation catalog.

The output JSON files under backend/data are application data, not model
weights or clinical guidance. Edit the seed records below, then rerun this
script to regenerate relationship IDs and keyword indexes consistently.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path


OUTPUT_DIR = Path(__file__).resolve().parents[1] / "backend" / "data"


def make_seed(
    identifier: str,
    name: str,
    parent: str,
    symptoms: tuple[str, ...],
    conditions: tuple[str, ...],
    treatments: tuple[str, ...],
    subspecialties: tuple[str, ...],
    keywords: tuple[str, ...],
    description: str,
    when_to_consult: str,
) -> dict[str, object]:
    return {
        "id": identifier,
        "name": name,
        "parent_category": parent,
        "symptoms": symptoms,
        "conditions": conditions,
        "treatments": treatments,
        "subspecialties": subspecialties,
        "keywords": keywords,
        "description": description,
        "when_to_consult": when_to_consult,
    }


SEEDS = [
    make_seed("general-medicine", "General Medicine", "Primary care", ("fever", "fatigue", "body ache", "loss of appetite"), ("viral illness", "hypertension", "diabetes screening", "anemia"), ("clinical assessment", "health screening", "medication review", "referral coordination"), ("Internal Medicine", "Preventive Medicine", "Chronic Disease Care", "Primary Care"), ("physician", "general doctor", "common illness", "medical checkup", "initial assessment", "family doctor"), "Provides first-contact care for common symptoms, long-term health concerns, and referral planning.", "Consult for a new, persistent, or unclear health concern when the right specialty is not obvious."),
    make_seed("cardiology", "Cardiology", "Medicine", ("chest discomfort", "palpitations", "shortness of breath", "leg swelling"), ("hypertension", "coronary artery disease", "heart failure", "arrhythmia"), ("ECG", "echocardiography", "cardiac risk assessment", "heart rhythm monitoring"), ("Interventional Cardiology", "Heart Failure Care", "Cardiac Imaging", "Electrophysiology"), ("heart doctor", "cardiac specialist", "blood pressure", "heart rhythm", "cholesterol", "chest symptoms"), "Focuses on the heart, circulation, and cardiovascular risk assessment.", "Consult for ongoing chest symptoms, heart-rhythm concerns, uncontrolled blood pressure, or a clinician-directed cardiac review."),
    make_seed("dermatology", "Dermatology", "Medicine", ("skin rash", "itching", "acne", "hair loss"), ("eczema", "psoriasis", "fungal infection", "acne"), ("skin examination", "dermoscopy", "topical treatment planning", "allergy patch testing"), ("Medical Dermatology", "Pediatric Dermatology", "Dermatopathology", "Cosmetic Dermatology"), ("skin doctor", "rash", "itchy skin", "pimples", "scalp", "nail problem"), "Cares for conditions affecting the skin, hair, nails, and related allergies.", "Consult for a persistent, spreading, painful, or recurrent skin, hair, or nail concern."),
    make_seed("endocrinology", "Endocrinology", "Medicine", ("increased thirst", "weight change", "heat intolerance", "irregular periods"), ("diabetes", "thyroid disorder", "osteoporosis", "PCOS"), ("blood sugar review", "thyroid testing", "hormone evaluation", "bone health assessment"), ("Diabetology", "Thyroid Care", "Metabolic Medicine", "Reproductive Endocrinology"), ("hormone doctor", "sugar level", "thyroid", "insulin", "metabolism", "endocrine"), "Focuses on hormones, metabolism, diabetes, thyroid conditions, and bone health.", "Consult for diabetes management, thyroid-related symptoms, unexplained metabolic changes, or hormone concerns."),
    make_seed("gastroenterology", "Gastroenterology", "Medicine", ("abdominal pain", "heartburn", "bloating", "change in bowel habit"), ("acid reflux", "irritable bowel syndrome", "fatty liver disease", "hepatitis"), ("digestive evaluation", "endoscopy planning", "liver assessment", "nutrition-related care"), ("Hepatology", "Inflammatory Bowel Disease", "Pancreatic Care", "Therapeutic Endoscopy"), ("stomach doctor", "digestion", "acidity", "liver", "bowel", "gastric"), "Cares for the digestive tract, liver, pancreas, and gastrointestinal symptoms.", "Consult for persistent digestive symptoms, recurrent abdominal pain, or a clinician-directed liver or bowel review."),
    make_seed("neurology", "Neurology", "Medicine", ("headache", "dizziness", "numbness", "tremor"), ("migraine", "epilepsy", "stroke follow-up", "neuropathy"), ("neurological examination", "nerve testing", "headache evaluation", "stroke rehabilitation planning"), ("Headache Medicine", "Epilepsy Care", "Movement Disorders", "Neuroimmunology"), ("brain doctor", "nerve doctor", "migraine", "seizure", "tingling", "vertigo"), "Focuses on the brain, spinal cord, nerves, and neurological symptoms.", "Consult for recurring headaches, seizure-related concerns, unexplained numbness, balance changes, or neurological follow-up."),
    make_seed("pulmonology", "Pulmonology", "Medicine", ("persistent cough", "wheezing", "breathlessness", "snoring"), ("asthma", "COPD", "pneumonia follow-up", "sleep apnea"), ("lung function testing", "inhaler review", "sleep study planning", "respiratory assessment"), ("Sleep Respiratory Care", "Interventional Pulmonology", "Asthma Care", "Critical Respiratory Care"), ("lung doctor", "breathing", "asthma", "cough", "wheezing", "sleep apnea"), "Cares for the lungs, airways, sleep-related breathing, and respiratory conditions.", "Consult for continuing cough, wheezing, breathlessness, or asthma and inhaler management concerns."),
    make_seed("nephrology", "Nephrology", "Medicine", ("swelling", "foamy urine", "reduced urine", "flank discomfort"), ("chronic kidney disease", "kidney stones", "proteinuria", "electrolyte disorder"), ("kidney function review", "urine testing", "dialysis planning", "blood pressure management"), ("Dialysis Medicine", "Glomerular Disease", "Kidney Transplant Care", "Hypertension and Kidney Care"), ("kidney doctor", "renal", "creatinine", "urine protein", "dialysis", "kidney function"), "Focuses on kidney function, fluid balance, blood pressure, and renal replacement care.", "Consult for abnormal kidney tests, recurrent swelling, urine changes, or kidney disease follow-up."),
    make_seed("rheumatology", "Rheumatology", "Medicine", ("joint swelling", "morning stiffness", "muscle pain", "fatigue"), ("rheumatoid arthritis", "lupus", "gout", "vasculitis"), ("autoimmune evaluation", "joint inflammation management", "infusion planning", "bone health review"), ("Autoimmune Disease Care", "Inflammatory Arthritis", "Connective Tissue Disease", "Pediatric Rheumatology"), ("arthritis doctor", "autoimmune", "joint swelling", "lupus", "gout", "rheumatic"), "Cares for autoimmune and inflammatory diseases affecting joints, muscles, and connective tissues.", "Consult for persistent joint swelling, morning stiffness, recurring inflammatory symptoms, or autoimmune-disease monitoring."),
    make_seed("hematology", "Hematology", "Medicine", ("easy bruising", "persistent fatigue", "frequent infections", "pale skin"), ("anemia", "bleeding disorder", "clotting disorder", "blood cell disorder"), ("blood count interpretation", "iron assessment", "clotting evaluation", "bone marrow assessment planning"), ("Benign Hematology", "Coagulation Care", "Transfusion Medicine", "Hematologic Malignancy Care"), ("blood doctor", "anemia", "low hemoglobin", "bleeding", "clotting", "blood count"), "Focuses on blood cells, clotting, anemia, and related disorders.", "Consult for persistent unexplained anemia, abnormal blood counts, easy bruising, or clinician-referred blood concerns."),
    make_seed("infectious-disease", "Infectious Disease", "Medicine", ("persistent fever", "recurrent infection", "night sweats", "travel-related illness"), ("tuberculosis", "dengue follow-up", "urinary infection", "viral infection"), ("infection evaluation", "antimicrobial review", "travel health counseling", "vaccination planning"), ("Travel Medicine", "Antimicrobial Stewardship", "HIV Medicine", "Tropical Medicine"), ("infection specialist", "fever specialist", "tropical disease", "antibiotic review", "TB", "dengue"), "Focuses on infections, prevention, antimicrobial use, and travel-related health risks.", "Consult for recurring, unexplained, or complicated infections, or when referred for infection management."),
    make_seed("medical-oncology", "Medical Oncology", "Medicine", ("unexplained weight loss", "persistent lump", "unusual bleeding", "prolonged fatigue"), ("solid tumor care", "cancer treatment planning", "cancer surveillance", "treatment side effects"), ("treatment planning", "systemic therapy counseling", "symptom support", "survivorship planning"), ("Breast Oncology", "Gastrointestinal Oncology", "Thoracic Oncology", "Geriatric Oncology"), ("cancer doctor", "oncology", "tumor", "chemotherapy", "cancer treatment", "cancer follow-up"), "Coordinates systemic cancer treatment, monitoring, symptom support, and survivorship care.", "Consult after a cancer diagnosis, for treatment planning, or when referred for an oncology opinion."),
    make_seed("geriatrics", "Geriatric Medicine", "Medicine", ("falls", "memory change", "multiple medicines", "frailty"), ("frailty syndrome", "dementia care", "polypharmacy", "osteoporosis"), ("comprehensive geriatric assessment", "fall-risk review", "medication review", "care planning"), ("Cognitive Geriatrics", "Falls Prevention", "Geriatric Rehabilitation", "Long-term Care"), ("elder care doctor", "senior health", "falls", "memory in old age", "multiple medicines", "frailty"), "Provides coordinated health care for older adults with multiple or complex needs.", "Consult for falls, memory changes, multiple medication concerns, frailty, or complex older-adult care planning."),
    make_seed("allergy-immunology", "Allergy and Immunology", "Medicine", ("hives", "sneezing", "recurrent wheeze", "food reaction"), ("allergic rhinitis", "urticaria", "food allergy", "immune deficiency evaluation"), ("allergy testing", "trigger assessment", "immunotherapy planning", "immune review"), ("Food Allergy Care", "Allergic Asthma", "Drug Allergy Care", "Clinical Immunology"), ("allergy doctor", "hives", "sneezing", "food allergy", "immune system", "allergic reaction"), "Assesses allergic reactions, immune-related concerns, and trigger-management options.", "Consult for recurring allergies, hives, suspected food or drug reactions, or clinician-directed immune evaluation."),
    make_seed("pediatrics", "Pediatrics", "Child health", ("child fever", "feeding difficulty", "cough in child", "poor weight gain"), ("common childhood illness", "growth concern", "childhood asthma", "developmental concern"), ("child health assessment", "growth monitoring", "vaccination counseling", "development review"), ("Developmental Pediatrics", "Adolescent Medicine", "Pediatric Emergency Care", "Pediatric Nutrition"), ("child doctor", "baby doctor", "pediatrician", "growth", "child fever", "vaccination"), "Provides general health care, prevention, growth monitoring, and illness assessment for children and adolescents.", "Consult for a child’s persistent symptoms, growth or development concerns, or routine pediatric care."),
    make_seed("neonatology", "Neonatology", "Child health", ("premature birth concern", "newborn feeding problem", "newborn jaundice", "low birth weight"), ("prematurity", "neonatal jaundice", "newborn infection", "respiratory distress in newborn"), ("newborn assessment", "NICU care", "feeding support", "newborn follow-up"), ("Neonatal Intensive Care", "High-risk Newborn Follow-up", "Neonatal Nutrition", "Neonatal Transport"), ("newborn doctor", "NICU", "premature baby", "newborn jaundice", "infant feeding", "neonatal"), "Cares for newborns, especially premature or medically complex infants.", "Consult through a maternity or pediatric team for a newborn health concern, especially after a high-risk birth."),
    make_seed("pediatric-cardiology", "Pediatric Cardiology", "Child health", ("child heart murmur", "blue lips", "poor feeding", "fainting in child"), ("congenital heart disease", "heart murmur", "pediatric arrhythmia", "Kawasaki disease follow-up"), ("pediatric echocardiography", "heart rhythm assessment", "congenital heart follow-up", "activity guidance"), ("Congenital Heart Care", "Pediatric Electrophysiology", "Fetal Cardiology", "Pediatric Heart Failure"), ("child heart doctor", "heart murmur", "congenital heart", "blue baby", "pediatric cardiac", "child palpitations"), "Focuses on heart conditions present in or affecting infants, children, and adolescents.", "Consult when a child is referred for a murmur, congenital heart condition, fainting, or cardiac symptoms."),
    make_seed("obstetrics-gynecology", "Obstetrics and Gynecology", "Women’s health", ("pelvic pain", "irregular periods", "abnormal bleeding", "pregnancy concern"), ("menstrual disorder", "uterine fibroids", "endometriosis", "pregnancy care"), ("gynecological examination", "prenatal care", "menstrual health assessment", "contraception counseling"), ("High-risk Obstetrics", "Gynecologic Surgery", "Menstrual Health", "Menopause Care"), ("women doctor", "gynecologist", "period problem", "pregnancy", "pelvic pain", "menstrual"), "Cares for reproductive health, pregnancy, gynecologic symptoms, and preventive women’s health.", "Consult for menstrual or pelvic symptoms, pregnancy care, contraception questions, or preventive gynecologic visits."),
    make_seed("reproductive-medicine", "Reproductive Medicine", "Women’s health", ("difficulty conceiving", "irregular ovulation", "recurrent pregnancy loss", "fertility concern"), ("infertility", "ovulatory disorder", "male factor infertility", "recurrent miscarriage evaluation"), ("fertility evaluation", "ovulation tracking", "assisted reproduction counseling", "preconception planning"), ("IVF Medicine", "Andrology", "Fertility Preservation", "Recurrent Pregnancy Loss Care"), ("fertility doctor", "infertility", "IVF", "trying to conceive", "ovulation", "reproductive health"), "Focuses on fertility assessment, assisted reproduction, and preconception planning.", "Consult after difficulty conceiving, for fertility evaluation, or when seeking reproductive planning support."),
    make_seed("maternal-fetal-medicine", "Maternal-Fetal Medicine", "Women’s health", ("high-risk pregnancy", "pregnancy hypertension", "gestational diabetes", "fetal growth concern"), ("high-risk pregnancy", "preeclampsia", "gestational diabetes", "multiple pregnancy"), ("high-risk prenatal assessment", "fetal ultrasound planning", "maternal health monitoring", "delivery planning"), ("Fetal Imaging", "Obstetric Medicine", "Multiple Pregnancy Care", "Genetic Counseling in Pregnancy"), ("high risk pregnancy", "pregnancy specialist", "gestational diabetes", "preeclampsia", "fetal growth", "maternal fetal"), "Provides specialist care for pregnancies with maternal, fetal, or obstetric risk factors.", "Consult when referred for a high-risk pregnancy, complex medical condition in pregnancy, or fetal-monitoring concern."),
    make_seed("orthopedics", "Orthopedics", "Musculoskeletal care", ("joint pain", "back pain", "bone injury", "limited movement"), ("osteoarthritis", "fracture", "sports injury", "spinal degeneration"), ("orthopedic examination", "fracture care", "joint replacement assessment", "mobility planning"), ("Joint Replacement", "Spine Surgery", "Trauma Orthopedics", "Hand and Upper Limb Care"), ("bone doctor", "orthopedic", "joint pain", "fracture", "back pain", "knee pain"), "Cares for bones, joints, ligaments, tendons, and musculoskeletal injuries.", "Consult for persistent joint or back pain, injury, fracture follow-up, or reduced movement."),
    make_seed("sports-medicine", "Sports Medicine", "Musculoskeletal care", ("exercise-related pain", "sprain", "overuse injury", "reduced performance"), ("tendon injury", "ligament injury", "stress fracture", "runner’s knee"), ("injury assessment", "return-to-sport planning", "exercise prescription", "injury prevention"), ("Running Medicine", "Shoulder Sports Care", "Knee Sports Care", "Exercise Physiology"), ("sports doctor", "gym injury", "sprain", "running pain", "athlete injury", "return to sport"), "Focuses on activity-related injuries, exercise health, and safe return to sport.", "Consult for a sports or exercise injury, recurrent pain with activity, or return-to-play planning."),
    make_seed("physical-medicine-rehabilitation", "Physical Medicine and Rehabilitation", "Rehabilitation", ("weakness", "mobility limitation", "chronic pain", "recovery after injury"), ("stroke rehabilitation", "spinal injury", "chronic pain", "functional limitation"), ("rehabilitation assessment", "assistive-device planning", "functional recovery plan", "spasticity management"), ("Neurorehabilitation", "Spinal Rehabilitation", "Amputee Rehabilitation", "Pain Rehabilitation"), ("rehab doctor", "physiatry", "mobility", "stroke recovery", "functional recovery", "rehabilitation"), "Helps restore function, independence, mobility, and quality of life after illness or injury.", "Consult for lasting mobility, function, or recovery needs after an injury, surgery, or neurological illness."),
    make_seed("pain-medicine", "Pain Medicine", "Rehabilitation", ("chronic pain", "nerve pain", "back pain", "pain affecting sleep"), ("chronic pain syndrome", "neuropathic pain", "complex regional pain", "cancer pain support"), ("pain assessment", "multimodal pain plan", "procedure counseling", "sleep and function review"), ("Interventional Pain Care", "Neuropathic Pain", "Cancer Pain Support", "Headache Pain Care"), ("pain doctor", "long term pain", "nerve pain", "pain clinic", "back pain", "chronic pain"), "Provides multidisciplinary assessment and management options for persistent or complex pain.", "Consult for pain lasting beyond expected recovery, pain limiting daily life, or specialist pain-management referral."),
    make_seed("general-surgery", "General Surgery", "Surgery", ("abdominal lump", "persistent hernia discomfort", "gallbladder pain", "surgical wound concern"), ("hernia", "gallstones", "appendicitis evaluation", "soft tissue lump"), ("surgical consultation", "preoperative assessment", "postoperative follow-up", "wound care planning"), ("Laparoscopic Surgery", "Breast Surgery", "Colorectal Surgery", "Hepatobiliary Surgery"), ("surgeon", "general surgery", "hernia", "gallbladder", "appendix", "operation"), "Provides surgical assessment and treatment planning for common abdominal, skin, breast, and soft-tissue conditions.", "Consult when referred for a possible operation, hernia, gallbladder concern, lump, or postoperative care."),
    make_seed("cardiothoracic-surgery", "Cardiothoracic Surgery", "Surgery", ("heart surgery referral", "chest surgical concern", "aortic condition", "lung surgery referral"), ("coronary artery disease surgery", "valve disease", "aortic aneurysm", "thoracic tumor"), ("surgical cardiac assessment", "valve surgery planning", "bypass surgery counseling", "thoracic surgery review"), ("Cardiac Surgery", "Aortic Surgery", "Thoracic Surgery", "Minimally Invasive Heart Surgery"), ("heart surgeon", "bypass surgery", "valve surgery", "chest surgeon", "aortic surgery", "thoracic surgery"), "Provides surgical care for the heart, major chest vessels, lungs, and chest structures.", "Consult after referral for cardiac, aortic, lung, or chest surgery assessment."),
    make_seed("neurosurgery", "Neurosurgery", "Surgery", ("nerve compression", "progressive weakness", "spinal pain with weakness", "brain surgery referral"), ("brain tumor", "spinal disc disease", "hydrocephalus", "nerve compression"), ("neurosurgical assessment", "spine surgery planning", "brain imaging review", "postoperative follow-up"), ("Brain Tumor Surgery", "Spine Neurosurgery", "Neurovascular Surgery", "Pediatric Neurosurgery"), ("brain surgeon", "spine surgeon", "neurosurgery", "disc surgery", "nerve compression", "brain operation"), "Provides surgical assessment for conditions affecting the brain, spine, and nervous system.", "Consult after a neurology or emergency referral for a structural brain, spine, or nerve condition requiring surgical review."),
    make_seed("plastic-reconstructive-surgery", "Plastic and Reconstructive Surgery", "Surgery", ("complex wound", "scar concern", "burn injury", "reconstruction referral"), ("burn injury", "complex wound", "scar contracture", "congenital difference"), ("wound reconstruction", "scar management", "burn care planning", "reconstructive consultation"), ("Burn Reconstruction", "Hand Reconstruction", "Craniofacial Surgery", "Microsurgery"), ("plastic surgeon", "reconstruction", "burn care", "scar", "wound repair", "hand reconstruction"), "Restores form and function after injury, burns, surgery, or congenital differences.", "Consult for complex wounds, burns, reconstructive needs, or referral after trauma or cancer surgery."),
    make_seed("urology", "Urology", "Surgery", ("painful urination", "blood in urine", "urinary frequency", "flank pain"), ("urinary tract stone", "prostate enlargement", "urinary infection", "incontinence"), ("urine evaluation", "stone assessment", "prostate review", "bladder function testing"), ("Endourology", "Andrology", "Female Urology", "Urologic Oncology"), ("urine doctor", "urologist", "kidney stone", "prostate", "urination", "bladder"), "Cares for the urinary tract, bladder, kidneys, prostate, and male reproductive system.", "Consult for recurring urinary symptoms, visible blood in urine, stone concerns, prostate symptoms, or urology referral."),
    make_seed("ophthalmology", "Ophthalmology", "Sensory health", ("blurred vision", "eye redness", "eye pain", "floaters"), ("cataract", "glaucoma", "dry eye", "retinal disorder"), ("eye examination", "vision testing", "retinal assessment", "cataract counseling"), ("Retina Care", "Glaucoma Care", "Cornea Care", "Pediatric Ophthalmology"), ("eye doctor", "vision", "cataract", "glaucoma", "red eye", "retina"), "Cares for eye health, vision, and conditions affecting the eye and visual pathways.", "Consult for persistent visual change, eye pain, redness, injury, or a scheduled eye health review."),
    make_seed("otolaryngology", "Otolaryngology", "Sensory health", ("ear pain", "hearing change", "sore throat", "nasal blockage"), ("sinusitis", "tonsil disorder", "ear infection", "voice disorder"), ("ear examination", "hearing evaluation", "sinus assessment", "voice assessment"), ("Rhinology", "Otology", "Laryngology", "Head and Neck Surgery"), ("ENT doctor", "ear nose throat", "sinus", "tonsil", "hearing", "voice problem"), "Cares for conditions affecting the ear, nose, throat, voice, and related head and neck structures.", "Consult for lasting ear, nose, throat, sinus, voice, or hearing symptoms."),
    make_seed("dentistry", "Dentistry", "Oral health", ("toothache", "gum bleeding", "jaw pain", "tooth sensitivity"), ("dental caries", "gum disease", "tooth infection", "jaw joint disorder"), ("dental examination", "oral hygiene planning", "restorative care planning", "jaw assessment"), ("Orthodontics", "Endodontics", "Periodontics", "Oral and Maxillofacial Surgery"), ("dentist", "tooth pain", "gums", "cavity", "oral health", "jaw pain"), "Cares for teeth, gums, oral hygiene, bite function, and oral health conditions.", "Consult for tooth or gum pain, swelling, sensitivity, oral injury, or preventive dental care."),
    make_seed("psychiatry", "Psychiatry", "Mental health", ("persistent low mood", "anxiety", "sleep change", "loss of interest"), ("depression", "anxiety disorder", "bipolar disorder", "substance use disorder"), ("mental health assessment", "medication review", "therapy coordination", "sleep review"), ("Addiction Psychiatry", "Child and Adolescent Psychiatry", "Geriatric Psychiatry", "Consultation-Liaison Psychiatry"), ("mental health doctor", "psychiatrist", "anxiety", "depression", "mood", "sleep problem"), "Provides medical assessment and treatment for mental health conditions and related symptoms.", "Consult for persistent changes in mood, anxiety, sleep, thought patterns, substance use, or clinician-referred mental health care."),
    make_seed("clinical-psychology", "Clinical Psychology", "Mental health", ("stress", "panic symptoms", "difficulty coping", "relationship distress"), ("anxiety disorder", "depression", "trauma-related stress", "behavioral concern"), ("psychological assessment", "talk therapy", "coping skills plan", "behavioral support"), ("Cognitive Behavioral Therapy", "Trauma-focused Care", "Health Psychology", "Child Psychology"), ("psychologist", "therapy", "stress", "counseling", "panic", "coping skills"), "Uses structured psychological assessment and evidence-informed talking therapies.", "Consult for stress, emotional distress, coping difficulties, behavior concerns, or therapy support."),
    make_seed("sleep-medicine", "Sleep Medicine", "Mental health", ("loud snoring", "daytime sleepiness", "insomnia", "restless sleep"), ("sleep apnea", "insomnia", "restless legs syndrome", "circadian rhythm disorder"), ("sleep assessment", "sleep study planning", "sleep hygiene coaching", "device therapy review"), ("Sleep Apnea Care", "Insomnia Care", "Circadian Medicine", "Pediatric Sleep Care"), ("sleep doctor", "snoring", "insomnia", "sleep apnea", "daytime sleepiness", "sleep study"), "Assesses and manages sleep disorders that affect rest, breathing, alertness, and daily functioning.", "Consult for persistent insomnia, loud snoring, witnessed breathing pauses, or severe daytime sleepiness."),
    make_seed("radiology", "Radiology", "Diagnostics", ("imaging referral", "unexplained pain imaging", "screening imaging", "injury imaging"), ("imaging abnormality", "fracture evaluation", "tumor imaging", "vascular imaging"), ("X-ray interpretation", "ultrasound", "CT planning", "MRI planning"), ("Neuroradiology", "Musculoskeletal Imaging", "Breast Imaging", "Interventional Radiology"), ("scan doctor", "X ray", "ultrasound", "CT scan", "MRI", "imaging"), "Uses medical imaging to support diagnosis, monitoring, and image-guided treatment planning.", "Consult through a referring clinician when imaging is needed or an image-guided procedure is planned."),
    make_seed("pathology", "Pathology", "Diagnostics", ("abnormal lab result", "biopsy referral", "blood test concern", "tissue sample review"), ("abnormal blood count", "biopsy finding", "infection testing", "tumor pathology"), ("laboratory testing", "tissue analysis", "blood testing", "diagnostic interpretation"), ("Anatomic Pathology", "Clinical Pathology", "Molecular Pathology", "Hematopathology"), ("lab doctor", "pathology", "biopsy", "blood test", "tissue test", "laboratory"), "Analyzes blood, tissue, and other samples to support accurate clinical diagnosis.", "Usually accessed through a referring clinician when laboratory tests or biopsy analysis are needed."),
    make_seed("emergency-medicine", "Emergency Medicine", "Urgent care", ("severe chest pain", "sudden weakness", "trouble breathing", "heavy bleeding"), ("acute injury", "severe infection", "allergic emergency", "stroke warning"), ("emergency assessment", "stabilization", "urgent imaging", "rapid referral"), ("Trauma Care", "Resuscitation", "Emergency Ultrasound", "Acute Toxicology"), ("emergency doctor", "accident", "severe pain", "cannot breathe", "bleeding", "urgent care"), "Provides immediate assessment and stabilization for acute illness, injury, and emergency warning signs.", "Seek emergency care now for severe or sudden symptoms, trouble breathing, major bleeding, loss of consciousness, or possible stroke symptoms."),
    make_seed("critical-care", "Critical Care Medicine", "Urgent care", ("organ support need", "severe infection", "critical illness", "ventilator care"), ("sepsis", "respiratory failure", "multi-organ failure", "shock"), ("ICU assessment", "organ support", "critical monitoring", "family care planning"), ("Medical ICU", "Surgical ICU", "Neurocritical Care", "Cardiac Critical Care"), ("ICU doctor", "critical care", "intensive care", "sepsis", "ventilator", "critical illness"), "Coordinates intensive monitoring and organ support for critically ill patients.", "Accessed through emergency or hospital teams when a person needs intensive or high-dependency hospital care."),
    make_seed("anesthesiology", "Anesthesiology", "Perioperative care", ("surgery preparation", "anesthesia concern", "postoperative pain", "airway concern"), ("perioperative risk", "anesthesia reaction history", "postoperative nausea", "acute pain"), ("pre-anesthesia evaluation", "anesthesia planning", "perioperative monitoring", "acute pain plan"), ("Cardiac Anesthesia", "Pediatric Anesthesia", "Obstetric Anesthesia", "Regional Anesthesia"), ("anesthesia doctor", "operation preparation", "surgery anesthesia", "postoperative pain", "pre anesthesia", "anesthetist"), "Plans safe anesthesia, monitoring, and perioperative pain support around procedures and surgery.", "Consult before a planned procedure when directed by a surgical or hospital team, especially with health or anesthesia concerns."),
    make_seed("family-medicine", "Family Medicine", "Primary care", ("common illness", "preventive care", "chronic condition follow-up", "family health concern"), ("hypertension", "diabetes", "common infection", "preventive health need"), ("family health assessment", "vaccination counseling", "chronic disease review", "preventive screening"), ("Community Family Care", "Women’s Primary Care", "Child and Family Care", "Chronic Disease Care"), ("family doctor", "primary care", "health check", "common illness", "preventive care", "family health"), "Provides ongoing, whole-person primary health care for people and families across life stages.", "Consult for routine care, prevention, common health problems, or coordination of longer-term health needs."),
    make_seed("public-health-preventive-medicine", "Public Health and Preventive Medicine", "Population health", ("vaccination question", "screening need", "workplace health concern", "travel prevention need"), ("vaccine-preventable illness", "occupational health risk", "screening need", "community health concern"), ("preventive counseling", "health screening", "vaccination planning", "risk assessment"), ("Occupational Health", "Travel Health", "Epidemiology", "Community Medicine"), ("preventive medicine", "public health", "screening", "vaccine", "occupational health", "health promotion"), "Focuses on prevention, screening, population health, occupational health, and health promotion.", "Consult for preventive screening, vaccination planning, workplace health questions, or community-health guidance."),
    make_seed("nutrition-dietetics", "Nutrition and Dietetics", "Allied health", ("diet concern", "unintended weight change", "poor appetite", "food intolerance question"), ("nutrition deficiency", "obesity", "diabetes nutrition care", "malnutrition risk"), ("nutrition assessment", "meal planning", "weight management plan", "therapeutic diet counseling"), ("Clinical Nutrition", "Sports Nutrition", "Pediatric Nutrition", "Renal Nutrition"), ("dietitian", "nutritionist", "meal plan", "weight management", "healthy eating", "diet advice"), "Provides nutrition assessment and practical food plans that support health conditions and goals.", "Consult for nutrition support, diet planning, weight changes, or a therapeutic diet recommended by a clinician."),
    make_seed("physiotherapy", "Physiotherapy", "Allied health", ("muscle weakness", "stiffness", "movement pain", "balance difficulty"), ("back pain", "postoperative recovery", "sports injury", "stroke recovery"), ("movement assessment", "exercise therapy", "manual therapy", "balance training"), ("Musculoskeletal Physiotherapy", "Neuro Physiotherapy", "Cardiorespiratory Physiotherapy", "Pelvic Health Physiotherapy"), ("physiotherapist", "physical therapy", "exercise rehab", "mobility", "back exercise", "pain movement"), "Uses movement, exercise, and rehabilitation techniques to support recovery, function, and mobility.", "Consult for pain with movement, recovery after injury or surgery, weakness, balance concerns, or rehabilitation planning."),
    make_seed("occupational-therapy", "Occupational Therapy", "Allied health", ("difficulty with daily activities", "hand function problem", "sensory difficulty", "work-related limitation"), ("functional limitation", "developmental disability support", "stroke recovery", "hand injury recovery"), ("daily living assessment", "adaptive equipment planning", "hand function training", "workplace adaptation"), ("Hand Therapy", "Pediatric Occupational Therapy", "Neurological Occupational Therapy", "Work Rehabilitation"), ("occupational therapist", "daily activities", "hand function", "adaptive equipment", "work rehab", "independence"), "Helps people build or regain independence in daily activities, work, school, and home routines.", "Consult for lasting difficulty with self-care, hand use, work tasks, sensory needs, or functional independence."),
    make_seed("speech-language-therapy", "Speech and Language Therapy", "Allied health", ("speech delay", "voice change", "swallowing difficulty", "communication difficulty"), ("language delay", "stuttering", "voice disorder", "dysphagia"), ("communication assessment", "speech therapy", "voice therapy", "swallowing assessment"), ("Pediatric Speech Therapy", "Voice Therapy", "Swallowing Therapy", "Neurogenic Communication Care"), ("speech therapist", "speech delay", "stuttering", "voice therapy", "swallowing", "language development"), "Assesses and treats communication, speech, language, voice, and swallowing difficulties.", "Consult for speech or language delay, voice changes, stuttering, communication difficulties, or swallowing concerns."),
    make_seed("audiology", "Audiology", "Allied health", ("hearing difficulty", "ringing in ears", "balance concern", "hearing aid question"), ("hearing loss", "tinnitus", "vestibular disorder", "noise-related hearing loss"), ("hearing test", "hearing aid assessment", "balance testing", "hearing protection counseling"), ("Pediatric Audiology", "Vestibular Audiology", "Hearing Device Care", "Occupational Audiology"), ("audiologist", "hearing test", "hearing aid", "tinnitus", "ear ringing", "balance test"), "Assesses hearing, balance-related inner-ear concerns, and hearing-device needs.", "Consult for hearing changes, tinnitus, balance symptoms, hearing-aid support, or a child’s hearing assessment."),
    make_seed("palliative-medicine", "Palliative Medicine", "Supportive care", ("serious illness symptoms", "complex pain", "breathlessness in serious illness", "caregiver strain"), ("advanced illness support", "cancer symptom support", "complex symptom burden", "goals of care planning"), ("symptom support", "care planning", "family support", "quality-of-life assessment"), ("Cancer Supportive Care", "Home-based Palliative Care", "Pediatric Palliative Care", "Pain and Symptom Support"), ("palliative care", "serious illness support", "comfort care", "caregiver support", "quality of life", "symptom support"), "Supports comfort, symptom control, communication, and quality of life alongside treatment for serious illness.", "Consult when a serious illness causes burdensome symptoms, complex decisions, or family and caregiver support needs."),
]


def slugify(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return normalized or "item"


def write_json(name: str, data: object) -> None:
    path = OUTPUT_DIR / name
    path.write_text(json.dumps(data, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def build_catalog() -> dict[str, int]:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    symptoms: dict[str, dict[str, object]] = {}
    conditions: dict[str, dict[str, object]] = {}
    treatments: dict[str, dict[str, object]] = {}
    subspecialties: list[dict[str, object]] = []
    specialty_rows: list[dict[str, object]] = []
    keyword_rows: list[dict[str, object]] = []

    def add_relation(store: dict[str, dict[str, object]], prefix: str, name: str, specialty_id: str) -> str:
        item_id = f"{prefix}-{slugify(name)}"
        row = store.setdefault(item_id, {"id": item_id, "name": name, "specialty_ids": []})
        row["specialty_ids"].append(specialty_id)
        return item_id

    for seed in SEEDS:
        specialty_id = str(seed["id"])
        symptom_ids = [add_relation(symptoms, "sym", item, specialty_id) for item in seed["symptoms"]]
        condition_ids = [add_relation(conditions, "cond", item, specialty_id) for item in seed["conditions"]]
        treatment_ids = [add_relation(treatments, "trt", item, specialty_id) for item in seed["treatments"]]
        subspecialty_ids: list[str] = []

        for name in seed["subspecialties"]:
            item_id = f"sub-{specialty_id}-{slugify(name)}"
            subspecialty_ids.append(item_id)
            subspecialties.append({
                "id": item_id,
                "specialty_id": specialty_id,
                "name": name,
                "description": f"A focused area within {seed['name']}.",
            })

        for term, kind in (
            [(seed["name"], "specialty")]
            + [(item, "symptom") for item in seed["symptoms"]]
            + [(item, "condition") for item in seed["conditions"]]
            + [(item, "treatment") for item in seed["treatments"]]
            + [(item, "subspecialty") for item in seed["subspecialties"]]
            + [(item, "related") for item in seed["keywords"]]
        ):
            keyword_rows.append({
                "id": f"kw-{specialty_id}-{kind}-{slugify(str(term))}",
                "term": term,
                "normalized_term": str(term).lower(),
                "specialty_ids": [specialty_id],
                "kind": kind,
            })

        specialty_rows.append({
            "id": specialty_id,
            "name": seed["name"],
            "parent_category": seed["parent_category"],
            "subspecialty_ids": subspecialty_ids,
            "common_symptom_ids": symptom_ids,
            "related_condition_ids": condition_ids,
            "treatment_ids": treatment_ids,
            "keyword_ids": [row["id"] for row in keyword_rows if specialty_id in row["specialty_ids"]],
            "description": seed["description"],
            "when_to_consult": seed["when_to_consult"],
        })

    for row in symptoms.values():
        row["aliases"] = [str(row["name"]).lower()]
    for row in conditions.values():
        row["description"] = f"A health topic associated with {len(row['specialty_ids'])} care area(s)."
    for row in treatments.values():
        row["description"] = f"A service commonly coordinated within {len(row['specialty_ids'])} care area(s)."

    write_json("specialties.json", specialty_rows)
    write_json("subspecialties.json", subspecialties)
    write_json("symptoms.json", list(symptoms.values()))
    write_json("conditions.json", list(conditions.values()))
    write_json("treatments.json", list(treatments.values()))
    write_json("medical_keywords.json", keyword_rows)

    counts = {
        "specialties": len(specialty_rows),
        "subspecialties": len(subspecialties),
        "symptoms": len(symptoms),
        "conditions": len(conditions),
        "treatments": len(treatments),
        "medical_keywords": len(keyword_rows),
    }
    counts["total_records"] = sum(counts.values())
    return counts


if __name__ == "__main__":
    summary = build_catalog()
    print("SmartCare medical catalog generated:")
    for name, count in summary.items():
        print(f"- {name}: {count}")
